version: '3.3'

services:
  # item is the service that lists the available items with their price.
  item:
    restart: always
    build:
      context: ./items
    ports:
      - '3001:80'
    volumes:
      - ./items:/var/www/html
    depends_on:
      - itemdb
  itemdb:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_DATABASE: 'shopmany'
      MYSQL_USER: 'hello'
      MYSQL_PASSWORD: 'ciao'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./items/db.sql:/docker-entrypoint-initdb.d/dump.sql

  # it manages the discouts available for every item.
  discount:
    image: node:10.15.3-stretch
    working_dir: /usr/src/app
    volumes:
      - ./discount:/usr/src/app
    command: ["node", "./server.js"]
    ports:
      - '3003:3000'
    depends_on:
      - discountdb
  discountdb:
    image: mongo:4.0.6-xenial
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "shopmany"
    ports:
      - '27017:27017'
    volumes:
      - ./discount/init:/docker-entrypoint-initdb.d

  # pay is a java app that handles items purchase
  pay:
    build:
      context: ./pay
    ports:
      - '3002:8080'

  # frontend is the ui of the project
  frontend:
    image: golang:1.12.0-stretch
    command: ["go", "run", "./main.go"]
    ports:
      - '3000:3000'
    volumes:
      - "./frontend:/opt/app"
    working_dir: "/opt/app"
    depends_on:
      - item
      - pay
      - discount
