version: '3.3'

services:
  item:
     #docker run -d -p 80:80 --name my-apache-php-app -v "$PWD":/var/www/html php:7.2-apache
    restart: always
    build:
      context: ./build/docker/item
    ports:
      - '3001:80'
    volumes:
      - ./items:/var/www/html
    depends_on:
      - itemdb
  itemdb:
    image: mysql:5.7.25
    restart: always
    environment:
      MYSQL_DATABASE: 'shopmany'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'hello'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ciao'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./items/db.sql:/docker-entrypoint-initdb.d/dump.sql
  discount:
    image: node:10.15.3-stretch
    working_dir: /usr/src/app
    volumes:
      - ./discount:/usr/src/app
    command: ["node", "./server.js"]
    ports:
      - '3000:3000'
    depends_on:
      - discountdb
  discountdb:
    image: mongo:4.0.6-xenial
    #build:
      #context: ./build/docker/discountdb
    restart: always
    environment:
      MONGO_INITDB_DATABASE: "shopmany"
    ports:
      - '27017:27017'
    volumes:
      - ./discount/init:/docker-entrypoint-initdb.d
