version: '3.3'

services:
  item:
     #docker run -d -p 80:80 --name my-apache-php-app -v "$PWD":/var/www/html php:7.2-apache
    restart: always
    build:
      context: ./build/docker/item
    ports:
      - 80:80
    volumes:
      - ./items:/var/www/html
  itemdb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'shopmany'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'hello'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'ciao'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/dump.sql
# Names our volume
volumes:
  my-db:
