-- MySQL Script generated by MySQL Workbench
-- Wed 06 Mar 2019 04:27:36 PM SAST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA IF NOT EXISTS  `pay` DEFAULT CHARACTER SET utf8 ;
USE `pay` ;

CREATE TABLE IF NOT EXISTS `pay`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` VARCHAR(45) NOT NULL,
  `tot_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

