-- MySQL Script generated by MySQL Workbench
-- Wed 06 Mar 2019 04:27:36 PM SAST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA  `shopmany`  ;
USE `shopmany` ;

CREATE TABLE `shopmany`.`payment` (
  `id` INT NOT NULL,
  `customer_id` VARCHAR(45) NOT NULL,
  `tot_price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

