-- MySQL Script generated by MySQL Workbench
-- Wed 06 Mar 2019 04:27:36 PM SAST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shopmany` DEFAULT CHARACTER SET utf8 ;
USE `shopmany` ;

-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shopmany`.`item` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(350) NOT NULL,
  `price` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Insert data
-- -----------------------------------------------------

INSERT INTO shopmany.item (id, name, description, price)
	VALUES(0, "Octo Cup", "The open cup movement is here. Join us.", 12.99);
INSERT INTO shopmany.item (id, name, description, price)
	VALUES(1, "Kubernetes Spinner", "Wait for a rolling update to go but with style.", 6.50);
INSERT INTO shopmany.item (id, name, description, price)
	VALUES(2, "Prometheus Socks", "A modern way to monitor 'smells like feet'", 4.10);
INSERT INTO shopmany.item (id, name, description, price)
	VALUES(3, "Google G - Short Sleeve", "The best way to make your lovely baby the smarter search engine ever.", 18.23);
